name: Switch Node version
on: 
  pull_request:

jobs:
  run-npm-test:
    runs-on: ubuntu-latest
    env:
      nodeversion: 14
    steps:
        - name: checkout
          uses: actions/checkout@v3
        - name : setup node
          uses: actions/setup-node@v3
          with:
            node-version: ${{env.nodeversion}}
        - name: run test
          shell: bash
          run: |
            npm install
            npm test
